In [1]:
import numpy as np

In [2]:
x = np.arange(6)

In [3]:
x

array([0, 1, 2, 3, 4, 5])

In [4]:
condlist = [x<3, x>3]



In [5]:
condlist

[array([ True,  True,  True, False, False, False]),
 array([False, False, False, False,  True,  True])]

In [6]:
choicelist = [x, x**2]

In [7]:
choicelist

[array([0, 1, 2, 3, 4, 5]), array([ 0,  1,  4,  9, 16, 25])]

In [8]:
np.select(condlist, choicelist, 42)

array([ 0,  1,  2, 42, 16, 25])

In [9]:
condlist = [x<=4, x>3]

In [10]:
condlist

[array([ True,  True,  True,  True,  True, False]),
 array([False, False, False, False,  True,  True])]

In [11]:
choicelist = [x, x**2]

In [12]:
choicelist

[array([0, 1, 2, 3, 4, 5]), array([ 0,  1,  4,  9, 16, 25])]

In [13]:
np.select(condlist, choicelist, 55)

array([ 0,  1,  2,  3,  4, 25])

In [ ]:
#Return an array drawn from elements in choicelist, depending on conditions.